/**
 * LessonExercise.jsx
 *
 * Renders the interactive exercise for a lesson.
 * Supports 8 exercise types generated by the backend:
 *   matching, syntax_sorting, multiple_choice, categorization,
 *   fill_blank, translation, dictation, flashcards
 *
 * After completion the user can:
 *   - See their score
 *   - Send results to Chat Tutor for explanation
 *   - Return to dashboard
 */
import { useCallback, useEffect, useMemo, useRef, useState } from 'react'
import { useLocation, useNavigate, useParams } from 'react-router-dom'
import { useTheme } from '../context/ThemeContext'
import api from '../services/api'

/* ── Helpers ──────────────────────────────────────────────────────── */

function shuffle(arr) {
  const a = [...arr]
  for (let i = a.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1))
    ;[a[i], a[j]] = [a[j], a[i]]
  }
  return a
}

function normalize(s) {
  return (s || '').trim().toLowerCase().replace(/[.,!?;:'"¿¡]/g, '')
}

/* ── TTS helper ───────────────────────────────────────────────────── */

function useAudioPlayer() {
  const [playing, setPlaying] = useState(false)
  const audioRef = useRef(null)

  const play = useCallback(async (texto, idioma) => {
    if (playing) return
    setPlaying(true)
    try {
      const resp = await api.post('/api/tts', { texto, idioma }, { responseType: 'blob' })
      const url = URL.createObjectURL(resp.data)
      if (audioRef.current) audioRef.current.pause()
      const audio = new Audio(url)
      audioRef.current = audio
      audio.onended = () => { setPlaying(false); URL.revokeObjectURL(url) }
      audio.onerror = () => { setPlaying(false); URL.revokeObjectURL(url) }
      await audio.play()
    } catch {
      setPlaying(false)
    }
  }, [playing])

  return { play, playing }
}

/* ── Reusable Audio Button ─────────────────────────────────────────── */

function AudioButton({ audioUrl, text, idioma, size = 'normal' }) {
  const [state, setState] = useState('idle') // idle | loading | playing
  const audioRef = useRef(null)
  const { play: fallbackPlay, playing: fallbackPlaying } = useAudioPlayer()

  async function handlePlay() {
    if (state === 'loading' || state === 'playing') return
    setState('loading')
    try {
      if (audioUrl) {
        // Use pre-cached audio from server
        if (audioRef.current) { audioRef.current.pause(); audioRef.current = null }
        const audio = new Audio(audioUrl)
        audioRef.current = audio
        audio.onended = () => setState('idle')
        audio.onerror = () => {
          // Fallback to on-demand TTS if cached file fails
          if (text && idioma) {
            fallbackPlay(text, idioma)
          }
          setState('idle')
        }
        audio.oncanplaythrough = () => {
          setState('playing')
          audio.play().catch(() => setState('idle'))
        }
        audio.load()
      } else if (text && idioma) {
        // On-demand TTS fallback
        setState('playing')
        await fallbackPlay(text, idioma)
        setState('idle')
      } else {
        setState('idle')
      }
    } catch {
      setState('idle')
    }
  }

  // Sync fallback player state
  useEffect(() => {
    if (!fallbackPlaying && state === 'playing' && !audioRef.current) {
      setState('idle')
    }
  }, [fallbackPlaying, state])

  const isLarge = size === 'large'
  const icon = state === 'loading' ? '⏳' : state === 'playing' ? '⏸️' : '🔊'

  return (
    <button
      onClick={handlePlay}
      disabled={state === 'loading'}
      className={`flex items-center gap-2 rounded-xl font-medium transition-all mb-3 ${
        isLarge
          ? 'w-full justify-center py-4 text-lg bg-primary-100 dark:bg-primary-900/30 text-primary-700 dark:text-primary-300 hover:bg-primary-200 dark:hover:bg-primary-900/50'
          : 'px-4 py-2 text-sm bg-primary-50 dark:bg-primary-900/20 text-primary-600 dark:text-primary-400 hover:bg-primary-100 dark:hover:bg-primary-900/40'
      }`}
    >
      <span className={isLarge ? 'text-2xl' : 'text-base'}>{icon}</span>
      <span>{state === 'loading' ? 'Cargando…' : state === 'playing' ? 'Reproduciendo…' : 'Escuchar audio'}</span>
    </button>
  )
}

/* ── Matching Exercise ────────────────────────────────────────────── */

function MatchingExercise({ data, onComplete }) {
  const pares = data.pares || []
  const [selected, setSelected] = useState({ left: null, right: null })
  const [matched, setMatched] = useState(new Set())
  const [errors, setErrors] = useState(0)
  const shuffledRight = useMemo(() => shuffle(pares.map((p, i) => ({ ...p, idx: i }))), [pares])

  function handleLeft(idx) {
    if (matched.has(idx)) return
    setSelected((s) => ({ ...s, left: idx }))
  }
  function handleRight(idx) {
    if (matched.has(idx)) return
    setSelected((s) => {
      const next = { ...s, right: idx }
      if (next.left !== null && next.right !== null) {
        if (next.left === next.right) {
          setMatched((m) => new Set([...m, next.left]))
        } else {
          setErrors((e) => e + 1)
        }
        return { left: null, right: null }
      }
      return next
    })
  }

  useEffect(() => {
    if (matched.size === pares.length && pares.length > 0) {
      const score = Math.max(0, Math.round(((pares.length - errors) / pares.length) * 100))
      onComplete(score)
    }
  }, [matched, pares.length, errors, onComplete])

  return (
    <div>
      <p className="text-sm text-gray-500 dark:text-gray-400 mb-4">{data.instrucciones}</p>
      <div className="grid grid-cols-2 gap-4">
        <div className="space-y-2">
          {pares.map((p, i) => (
            <button
              key={`l-${i}`}
              onClick={() => handleLeft(i)}
              disabled={matched.has(i)}
              className={`w-full text-left px-4 py-3 rounded-xl border text-sm transition-all ${
                matched.has(i)
                  ? 'bg-green-100 dark:bg-green-900/30 border-green-300 dark:border-green-700 text-green-700 dark:text-green-400 line-through'
                  : selected.left === i
                    ? 'border-primary-500 bg-primary-50 dark:bg-primary-900/30'
                    : 'border-gray-200 dark:border-gray-700 hover:border-primary-300'
              }`}
            >
              {p.termino}
            </button>
          ))}
        </div>
        <div className="space-y-2">
          {shuffledRight.map((p) => (
            <button
              key={`r-${p.idx}`}
              onClick={() => handleRight(p.idx)}
              disabled={matched.has(p.idx)}
              className={`w-full text-left px-4 py-3 rounded-xl border text-sm transition-all ${
                matched.has(p.idx)
                  ? 'bg-green-100 dark:bg-green-900/30 border-green-300 dark:border-green-700 text-green-700 dark:text-green-400 line-through'
                  : selected.right === p.idx
                    ? 'border-primary-500 bg-primary-50 dark:bg-primary-900/30'
                    : 'border-gray-200 dark:border-gray-700 hover:border-primary-300'
              }`}
            >
              {p.definicion}
            </button>
          ))}
        </div>
      </div>
    </div>
  )
}

/* ── Syntax Sorting Exercise ──────────────────────────────────────── */

function SyntaxSortingExercise({ data, onComplete }) {
  const ejercicios = data.ejercicios || []
  const [current, setCurrent] = useState(0)
  const [placed, setPlaced] = useState([])
  const [pool, setPool] = useState([])
  const [results, setResults] = useState([])

  useEffect(() => {
    if (ejercicios[current]) {
      setPlaced([])
      setPool(shuffle(ejercicios[current].palabras_desordenadas || []))
    }
  }, [current, ejercicios])

  function addWord(word, idx) {
    setPlaced((p) => [...p, word])
    setPool((p) => p.filter((_, i) => i !== idx))
  }
  function removeWord(idx) {
    const word = placed[idx]
    setPlaced((p) => p.filter((_, i) => i !== idx))
    setPool((p) => [...p, word])
  }
  function checkAndNext() {
    const answer = placed.join(' ')
    const correct = normalize(answer) === normalize(ejercicios[current].frase_correcta)
    const newResults = [...results, correct]
    setResults(newResults)
    if (current + 1 < ejercicios.length) {
      setCurrent(current + 1)
    } else {
      const score = Math.round((newResults.filter(Boolean).length / newResults.length) * 100)
      onComplete(score)
    }
  }

  if (!ejercicios[current]) return null

  return (
    <div>
      <p className="text-sm text-gray-500 dark:text-gray-400 mb-2">{data.instrucciones}</p>
      <p className="text-xs text-gray-400 dark:text-gray-500 mb-4">Ejercicio {current + 1} de {ejercicios.length}</p>

      <p className="font-medium text-gray-700 dark:text-gray-200 mb-3">
        {ejercicios[current].traduccion}
      </p>

      {/* Placed words */}
      <div className="min-h-[48px] border-2 border-dashed border-gray-300 dark:border-gray-600 rounded-xl p-3 mb-4 flex flex-wrap gap-2">
        {placed.length === 0 && <span className="text-xs text-gray-400">Toca las palabras para armar la oración…</span>}
        {placed.map((w, i) => (
          <button key={i} onClick={() => removeWord(i)} className="px-3 py-1.5 bg-primary-600 text-white rounded-lg text-sm font-medium hover:bg-primary-700 transition-colors">
            {w}
          </button>
        ))}
      </div>

      {/* Word pool */}
      <div className="flex flex-wrap gap-2 mb-4">
        {pool.map((w, i) => (
          <button key={i} onClick={() => addWord(w, i)} className="px-3 py-1.5 bg-gray-100 dark:bg-gray-800 text-gray-700 dark:text-gray-300 rounded-lg text-sm font-medium hover:bg-gray-200 dark:hover:bg-gray-700 transition-colors">
            {w}
          </button>
        ))}
      </div>

      <button
        onClick={checkAndNext}
        disabled={placed.length === 0}
        className="btn-primary"
      >
        {current + 1 < ejercicios.length ? 'Siguiente →' : 'Finalizar ✓'}
      </button>
    </div>
  )
}

/* ── Multiple Choice Exercise ─────────────────────────────────────── */

function MultipleChoiceExercise({ data, onComplete, idioma }) {
  const preguntas = data.preguntas || []
  const [current, setCurrent] = useState(0)
  const [selected, setSelected] = useState(null)
  const [showResult, setShowResult] = useState(false)
  const [results, setResults] = useState([])

  function selectOption(idx) {
    if (showResult) return
    setSelected(idx)
    setShowResult(true)
    const correct = idx === preguntas[current].respuesta_correcta
    setResults((r) => [...r, correct])
  }

  function next() {
    setSelected(null)
    setShowResult(false)
    if (current + 1 < preguntas.length) {
      setCurrent(current + 1)
    } else {
      const score = Math.round((results.filter(Boolean).length / results.length) * 100)
      onComplete(score)
    }
  }

  if (!preguntas[current]) return null
  const q = preguntas[current]
  const hasAudio = !!q.audio_url || !!q.audio_texto

  return (
    <div>
      <p className="text-sm text-gray-500 dark:text-gray-400 mb-2">{data.instrucciones}</p>
      <p className="text-xs text-gray-400 dark:text-gray-500 mb-4">Pregunta {current + 1} de {preguntas.length}</p>

      {/* Audio player for listening exercises */}
      {hasAudio && (
        <AudioButton
          audioUrl={q.audio_url}
          text={q.audio_texto}
          idioma={idioma}
          size="large"
        />
      )}

      <p className="text-lg font-semibold text-gray-800 dark:text-gray-100 mb-4">{q.pregunta}</p>

      <div className="space-y-2 mb-4">
        {q.opciones.map((opt, i) => (
          <button
            key={i}
            onClick={() => selectOption(i)}
            className={`w-full text-left px-4 py-3 rounded-xl border text-sm transition-all ${
              showResult
                ? i === q.respuesta_correcta
                  ? 'bg-green-100 dark:bg-green-900/30 border-green-500 text-green-800 dark:text-green-300'
                  : i === selected
                    ? 'bg-red-100 dark:bg-red-900/30 border-red-500 text-red-800 dark:text-red-300'
                    : 'border-gray-200 dark:border-gray-700 text-gray-500'
                : 'border-gray-200 dark:border-gray-700 hover:border-primary-300 dark:hover:border-primary-600 text-gray-800 dark:text-gray-200'
            }`}
          >
            {opt}
          </button>
        ))}
      </div>

      {showResult && q.explicacion && (
        <div className="bg-blue-50 dark:bg-blue-900/30 border border-blue-200 dark:border-blue-800 rounded-xl px-4 py-3 text-sm text-blue-700 dark:text-blue-300 mb-4">
          💡 {q.explicacion}
        </div>
      )}

      {showResult && (
        <button onClick={next} className="btn-primary">
          {current + 1 < preguntas.length ? 'Siguiente →' : 'Finalizar ✓'}
        </button>
      )}
    </div>
  )
}

/* ── Categorization Exercise ──────────────────────────────────────── */

function CategorizationExercise({ data, onComplete }) {
  const categorias = data.categorias || []
  const palabras = useMemo(() => shuffle(data.palabras || []), [data.palabras])
  const [placed, setPlaced] = useState({})  // word index → category index
  const [currentWord, setCurrentWord] = useState(0)
  const [results, setResults] = useState([])

  function placeInCategory(catIdx) {
    const word = palabras[currentWord]
    const correct = word.categoria === catIdx
    setPlaced((p) => ({ ...p, [currentWord]: catIdx }))
    setResults((r) => [...r, correct])

    if (currentWord + 1 < palabras.length) {
      setCurrentWord(currentWord + 1)
    } else {
      const allResults = [...results, correct]
      const score = Math.round((allResults.filter(Boolean).length / allResults.length) * 100)
      onComplete(score)
    }
  }

  if (!palabras[currentWord]) return null

  return (
    <div>
      <p className="text-sm text-gray-500 dark:text-gray-400 mb-2">{data.instrucciones}</p>
      <p className="text-xs text-gray-400 dark:text-gray-500 mb-4">Palabra {currentWord + 1} de {palabras.length}</p>

      {/* Current word */}
      <div className="text-center mb-6">
        <span className="inline-block px-6 py-3 bg-primary-50 dark:bg-primary-900/30 text-primary-700 dark:text-primary-300 rounded-2xl text-xl font-bold">
          {palabras[currentWord].palabra}
        </span>
      </div>

      {/* Category buttons */}
      <div className="grid grid-cols-2 gap-4">
        {categorias.map((cat, i) => (
          <button
            key={i}
            onClick={() => placeInCategory(i)}
            className="card hover:shadow-lg transition-all text-center py-6 border-2 border-transparent hover:border-primary-500"
          >
            <p className="font-semibold text-gray-800 dark:text-gray-100">{cat}</p>
            <p className="text-xs text-gray-400 mt-1">
              {Object.entries(placed).filter(([, v]) => v === i).length} palabras
            </p>
          </button>
        ))}
      </div>
    </div>
  )
}

/* ── Fill in the Blank Exercise ───────────────────────────────────── */

function FillBlankExercise({ data, onComplete, idioma }) {
  const ejercicios = data.ejercicios || []
  const [current, setCurrent] = useState(0)
  const [answer, setAnswer] = useState('')
  const [showResult, setShowResult] = useState(false)
  const [isCorrect, setIsCorrect] = useState(false)
  const [results, setResults] = useState([])

  function check() {
    const correct = normalize(answer) === normalize(ejercicios[current].respuesta)
    setIsCorrect(correct)
    setShowResult(true)
    setResults((r) => [...r, correct])
  }

  function next() {
    setAnswer('')
    setShowResult(false)
    setIsCorrect(false)
    if (current + 1 < ejercicios.length) {
      setCurrent(current + 1)
    } else {
      const score = Math.round((results.filter(Boolean).length / results.length) * 100)
      onComplete(score)
    }
  }

  if (!ejercicios[current]) return null
  const ex = ejercicios[current]
  const hasAudio = !!ex.audio_url || !!ex.audio_texto

  return (
    <div>
      <p className="text-sm text-gray-500 dark:text-gray-400 mb-2">{data.instrucciones}</p>
      <p className="text-xs text-gray-400 dark:text-gray-500 mb-4">Ejercicio {current + 1} de {ejercicios.length}</p>

      {hasAudio && (
        <AudioButton
          audioUrl={ex.audio_url}
          text={ex.audio_texto}
          idioma={idioma}
          size="large"
        />
      )}

      <p className="text-lg font-medium text-gray-800 dark:text-gray-100 mb-2">{ex.oracion}</p>
      {ex.pista && <p className="text-xs text-gray-400 dark:text-gray-500 mb-3">💡 Pista: {ex.pista}</p>}

      <input
        type="text"
        className="input mb-3"
        placeholder="Escribe tu respuesta…"
        value={answer}
        onChange={(e) => setAnswer(e.target.value)}
        disabled={showResult}
        onKeyDown={(e) => e.key === 'Enter' && !showResult && check()}
      />

      {showResult && (
        <div className={`rounded-xl px-4 py-3 text-sm mb-3 ${
          isCorrect
            ? 'bg-green-50 dark:bg-green-900/30 text-green-700 dark:text-green-400'
            : 'bg-red-50 dark:bg-red-900/30 text-red-700 dark:text-red-400'
        }`}>
          {isCorrect ? '✅ ¡Correcto!' : `❌ La respuesta correcta es: "${ex.respuesta}"`}
        </div>
      )}

      {!showResult ? (
        <button onClick={check} disabled={!answer.trim()} className="btn-primary">Verificar</button>
      ) : (
        <button onClick={next} className="btn-primary">
          {current + 1 < ejercicios.length ? 'Siguiente →' : 'Finalizar ✓'}
        </button>
      )}
    </div>
  )
}

/* ── Translation Exercise ─────────────────────────────────────────── */

function TranslationExercise({ data, onComplete }) {
  const ejercicios = data.ejercicios || []
  const [current, setCurrent] = useState(0)
  const [answer, setAnswer] = useState('')
  const [showResult, setShowResult] = useState(false)
  const [isCorrect, setIsCorrect] = useState(false)
  const [results, setResults] = useState([])

  function check() {
    const ex = ejercicios[current]
    const allValid = [ex.traduccion_correcta, ...(ex.traducciones_alternativas || [])].map(normalize)
    const correct = allValid.includes(normalize(answer))
    setIsCorrect(correct)
    setShowResult(true)
    setResults((r) => [...r, correct])
  }

  function next() {
    setAnswer('')
    setShowResult(false)
    setIsCorrect(false)
    if (current + 1 < ejercicios.length) {
      setCurrent(current + 1)
    } else {
      const score = Math.round((results.filter(Boolean).length / results.length) * 100)
      onComplete(score)
    }
  }

  if (!ejercicios[current]) return null
  const ex = ejercicios[current]

  return (
    <div>
      <p className="text-sm text-gray-500 dark:text-gray-400 mb-2">{data.instrucciones}</p>
      <p className="text-xs text-gray-400 dark:text-gray-500 mb-4">Ejercicio {current + 1} de {ejercicios.length}</p>

      <div className="bg-gray-50 dark:bg-gray-800 rounded-xl px-4 py-3 mb-4">
        <p className="text-lg font-medium text-gray-800 dark:text-gray-100">{ex.texto_original}</p>
      </div>

      <textarea
        className="input mb-3 resize-none"
        rows={2}
        placeholder="Escribe la traducción completa…"
        value={answer}
        onChange={(e) => setAnswer(e.target.value)}
        disabled={showResult}
      />

      {showResult && (
        <div className={`rounded-xl px-4 py-3 text-sm mb-3 ${
          isCorrect
            ? 'bg-green-50 dark:bg-green-900/30 text-green-700 dark:text-green-400'
            : 'bg-red-50 dark:bg-red-900/30 text-red-700 dark:text-red-400'
        }`}>
          {isCorrect ? '✅ ¡Correcto!' : `❌ Respuesta esperada: "${ex.traduccion_correcta}"`}
        </div>
      )}

      {!showResult ? (
        <button onClick={check} disabled={!answer.trim()} className="btn-primary">Verificar</button>
      ) : (
        <button onClick={next} className="btn-primary">
          {current + 1 < ejercicios.length ? 'Siguiente →' : 'Finalizar ✓'}
        </button>
      )}
    </div>
  )
}

/* ── Dictation Exercise ───────────────────────────────────────────── */

function DictationExercise({ data, idioma, onComplete }) {
  const ejercicios = data.ejercicios || []
  const [current, setCurrent] = useState(0)
  const [answer, setAnswer] = useState('')
  const [showResult, setShowResult] = useState(false)
  const [isCorrect, setIsCorrect] = useState(false)
  const [results, setResults] = useState([])

  function check() {
    const correct = normalize(answer) === normalize(ejercicios[current].texto)
    setIsCorrect(correct)
    setShowResult(true)
    setResults((r) => [...r, correct])
  }

  function next() {
    setAnswer('')
    setShowResult(false)
    setIsCorrect(false)
    if (current + 1 < ejercicios.length) {
      setCurrent(current + 1)
    } else {
      const score = Math.round((results.filter(Boolean).length / results.length) * 100)
      onComplete(score)
    }
  }

  if (!ejercicios[current]) return null
  const ex = ejercicios[current]

  return (
    <div>
      <p className="text-sm text-gray-500 dark:text-gray-400 mb-2">{data.instrucciones}</p>
      <p className="text-xs text-gray-400 dark:text-gray-500 mb-4">Ejercicio {current + 1} de {ejercicios.length}</p>

      <AudioButton
        audioUrl={ex.audio_url}
        text={ex.texto}
        idioma={idioma}
        size="large"
      />

      <input
        type="text"
        className="input mb-3"
        placeholder="Escribe lo que escuchaste…"
        value={answer}
        onChange={(e) => setAnswer(e.target.value)}
        disabled={showResult}
        onKeyDown={(e) => e.key === 'Enter' && !showResult && check()}
      />

      {showResult && (
        <div className={`rounded-xl px-4 py-3 text-sm mb-3 ${
          isCorrect
            ? 'bg-green-50 dark:bg-green-900/30 text-green-700 dark:text-green-400'
            : 'bg-red-50 dark:bg-red-900/30 text-red-700 dark:text-red-400'
        }`}>
          {isCorrect ? '✅ ¡Correcto!' : `❌ El texto era: "${ex.texto}"`}
          {ex.traduccion && (
            <p className="text-xs mt-1 opacity-75">Traducción: {ex.traduccion}</p>
          )}
        </div>
      )}

      {!showResult ? (
        <button onClick={check} disabled={!answer.trim()} className="btn-primary">Verificar</button>
      ) : (
        <button onClick={next} className="btn-primary">
          {current + 1 < ejercicios.length ? 'Siguiente →' : 'Finalizar ✓'}
        </button>
      )}
    </div>
  )
}

/* ── Flashcards Exercise ──────────────────────────────────────────── */

function FlashcardsExercise({ data, onComplete }) {
  const tarjetas = data.tarjetas || []
  const [current, setCurrent] = useState(0)
  const [flipped, setFlipped] = useState(false)
  const [results, setResults] = useState([])

  function rate(difficulty) {
    // Easy=100, Medium=60, Hard=20
    const score = difficulty === 'easy' ? 100 : difficulty === 'medium' ? 60 : 20
    setResults((r) => [...r, score])
    setFlipped(false)
    if (current + 1 < tarjetas.length) {
      setCurrent(current + 1)
    } else {
      const allResults = [...results, score]
      const avg = Math.round(allResults.reduce((a, b) => a + b, 0) / allResults.length)
      onComplete(avg)
    }
  }

  if (!tarjetas[current]) return null
  const card = tarjetas[current]

  return (
    <div>
      <p className="text-sm text-gray-500 dark:text-gray-400 mb-2">{data.instrucciones}</p>
      <p className="text-xs text-gray-400 dark:text-gray-500 mb-4">Tarjeta {current + 1} de {tarjetas.length}</p>

      {/* Card */}
      <button
        onClick={() => setFlipped(!flipped)}
        className="w-full min-h-[200px] card hover:shadow-lg transition-all flex flex-col items-center justify-center text-center p-8 mb-4"
      >
        {!flipped ? (
          <>
            <p className="text-2xl font-bold text-gray-800 dark:text-gray-100">{card.frente}</p>
            <p className="text-xs text-gray-400 mt-4">Toca para voltear →</p>
          </>
        ) : (
          <>
            <p className="text-xl font-semibold text-primary-600 dark:text-primary-400">{card.reverso}</p>
            {card.ejemplo && (
              <p className="text-sm text-gray-500 dark:text-gray-400 mt-3 italic">"{card.ejemplo}"</p>
            )}
          </>
        )}
      </button>

      {/* Rating buttons (only after flip) */}
      {flipped && (
        <div className="grid grid-cols-3 gap-3">
          <button onClick={() => rate('hard')} className="py-3 rounded-xl bg-red-100 dark:bg-red-900/30 text-red-700 dark:text-red-400 font-semibold hover:bg-red-200 dark:hover:bg-red-900/50 transition-colors">
            😣 Difícil
          </button>
          <button onClick={() => rate('medium')} className="py-3 rounded-xl bg-amber-100 dark:bg-amber-900/30 text-amber-700 dark:text-amber-400 font-semibold hover:bg-amber-200 dark:hover:bg-amber-900/50 transition-colors">
            🤔 Medio
          </button>
          <button onClick={() => rate('easy')} className="py-3 rounded-xl bg-green-100 dark:bg-green-900/30 text-green-700 dark:text-green-400 font-semibold hover:bg-green-200 dark:hover:bg-green-900/50 transition-colors">
            😊 Fácil
          </button>
        </div>
      )}
    </div>
  )
}

/* ── Main LessonExercise Page ─────────────────────────────────────── */

export default function LessonExercise() {
  const { id } = useParams()
  const location = useLocation()
  const navigate = useNavigate()
  const { dark, toggle } = useTheme()

  const [lesson, setLesson] = useState(location.state?.lesson || null)
  const [loading, setLoading] = useState(!lesson)
  const [completed, setCompleted] = useState(false)
  const [score, setScore] = useState(0)
  const [saving, setSaving] = useState(false)

  // Fetch lesson if not passed via navigation state
  useEffect(() => {
    if (!lesson) {
      api.get('/api/leccion/lista').then(({ data }) => {
        const found = data.find((l) => l.id === parseInt(id))
        if (found) setLesson(found)
        setLoading(false)
      }).catch(() => setLoading(false))
    }
  }, [id, lesson])

  const exerciseData = useMemo(() => {
    if (!lesson) return null
    try {
      return JSON.parse(lesson.contenido)
    } catch {
      return null
    }
  }, [lesson])

  const handleComplete = useCallback(async (finalScore) => {
    setScore(finalScore)
    setCompleted(true)
    setSaving(true)
    try {
      await api.post(`/api/leccion/${lesson.id}/completar`, {
        puntuacion: finalScore,
        resultado_json: JSON.stringify({ score: finalScore }),
      })
    } catch {
      // Lesson may already be completed
    } finally {
      setSaving(false)
    }
  }, [lesson])

  function sendToChatTutor() {
    navigate('/chat', {
      state: {
        lesson: { ...lesson, puntuacion: score },
        autoSend: true,
      },
    })
  }

  if (loading) {
    return (
      <div className="min-h-screen bg-surface-light dark:bg-surface-dark flex items-center justify-center">
        <span className="text-gray-400">Cargando lección…</span>
      </div>
    )
  }

  if (!lesson || !exerciseData) {
    return (
      <div className="min-h-screen bg-surface-light dark:bg-surface-dark flex flex-col items-center justify-center gap-4">
        <p className="text-gray-500 dark:text-gray-400">No se pudo cargar la lección.</p>
        <button onClick={() => navigate('/dashboard')} className="btn-primary">Volver al Dashboard</button>
      </div>
    )
  }

  return (
    <div className="min-h-screen bg-surface-light dark:bg-surface-dark transition-colors duration-300">
      {/* Header */}
      <header className="bg-card-light dark:bg-card-dark shadow-sm dark:shadow-black/20 sticky top-0 z-10 transition-colors duration-300">
        <div className="max-w-3xl mx-auto px-4 py-3 flex items-center justify-between">
          <div className="flex items-center gap-3">
            <button onClick={() => navigate('/dashboard')} className="text-gray-400 hover:text-primary-600 dark:hover:text-primary-400 transition-colors" aria-label="Volver">
              ←
            </button>
            <img src="/logo.jpg" alt="PolyIA" className="w-8 h-8 rounded-full object-cover" />
            <div>
              <h1 className="text-sm font-bold text-primary-600 dark:text-primary-400 truncate max-w-[200px] sm:max-w-none">{lesson.tema}</h1>
              <p className="text-xs text-gray-400 dark:text-gray-500">{lesson.nivel} · {lesson.tipo_ejercicio.replace('_', ' ')}</p>
            </div>
          </div>
          <button onClick={toggle} className="p-1.5 rounded-full hover:bg-gray-100 dark:hover:bg-gray-700 transition-colors" aria-label="Cambiar tema">
            {dark ? '☀️' : '🌙'}
          </button>
        </div>
      </header>

      <main className="max-w-3xl mx-auto px-4 py-8">
        {/* ── Completed screen ── */}
        {completed ? (
          <div className="card text-center py-12 space-y-4">
            <span className="text-6xl">{score >= 80 ? '🎉' : score >= 50 ? '👍' : '💪'}</span>
            <h2 className="text-2xl font-bold text-gray-800 dark:text-gray-100">
              {score >= 80 ? '¡Excelente!' : score >= 50 ? '¡Buen trabajo!' : '¡Sigue practicando!'}
            </h2>
            <p className="text-4xl font-bold text-primary-600 dark:text-primary-400">{score}%</p>
            {saving && <p className="text-sm text-gray-400">Guardando progreso…</p>}

            <div className="flex flex-col sm:flex-row gap-3 justify-center pt-4">
              <button onClick={() => navigate('/dashboard')} className="btn-primary">
                ← Volver al Dashboard
              </button>
              <button onClick={sendToChatTutor} className="px-5 py-2.5 rounded-xl border border-primary-500 text-primary-600 dark:text-primary-400 font-semibold hover:bg-primary-50 dark:hover:bg-primary-900/30 transition-colors">
                🤖 Enviar al Chat Tutor
              </button>
            </div>
          </div>
        ) : lesson.completada ? (
          /* Already completed lesson — show read-only info */
          <div className="card text-center py-12 space-y-4">
            <span className="text-6xl">✅</span>
            <h2 className="text-2xl font-bold text-gray-800 dark:text-gray-100">Lección ya completada</h2>
            <p className="text-4xl font-bold text-primary-600 dark:text-primary-400">{lesson.puntuacion}%</p>
            <button onClick={() => navigate('/dashboard')} className="btn-primary">← Volver al Dashboard</button>
          </div>
        ) : (
          /* ── Active exercise ── */
          <div className="card">
            {lesson.tipo_ejercicio === 'matching' && (
              <MatchingExercise data={exerciseData} onComplete={handleComplete} />
            )}
            {lesson.tipo_ejercicio === 'syntax_sorting' && (
              <SyntaxSortingExercise data={exerciseData} onComplete={handleComplete} />
            )}
            {lesson.tipo_ejercicio === 'multiple_choice' && (
              <MultipleChoiceExercise data={exerciseData} onComplete={handleComplete} idioma={lesson.idioma} />
            )}
            {lesson.tipo_ejercicio === 'categorization' && (
              <CategorizationExercise data={exerciseData} onComplete={handleComplete} />
            )}
            {lesson.tipo_ejercicio === 'fill_blank' && (
              <FillBlankExercise data={exerciseData} onComplete={handleComplete} idioma={lesson.idioma} />
            )}
            {lesson.tipo_ejercicio === 'translation' && (
              <TranslationExercise data={exerciseData} onComplete={handleComplete} />
            )}
            {lesson.tipo_ejercicio === 'dictation' && (
              <DictationExercise data={exerciseData} idioma={lesson.idioma} onComplete={handleComplete} />
            )}
            {lesson.tipo_ejercicio === 'flashcards' && (
              <FlashcardsExercise data={exerciseData} onComplete={handleComplete} />
            )}
          </div>
        )}
      </main>
    </div>
  )
}
